backend:
  name: git-gateway
  branch: main  # Replace with your default branch name

media_folder: "assets/images"  # Path to images in the repository
public_folder: "/assets/images"  # Path to images in the published site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
